WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 800
FPS = 60

OBSTACLE_COUNT = 7
OBSTACLE_MIN_R = 55
OBSTACLE_MAX_R = 100

ENEMY_COUNT = 35
ATTACK_THRESHOLD = 8       # minimalna liczba botów do rozpoczęcia ataku